name: "CI: Static Analysis and Tests"

on:
    pull_request:
    push:
        branches:
            - "main"

jobs:
    static-analysis:
        name: "Static Analysis"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  php-version: "8.1"

            - name: "Validate Composer"
              run: "composer validate"

            - name: "Install dependencies"
              run: "composer install --no-interaction --no-progress"

            - name: "PHPStan"
              run: "bin/phpstan analyse --no-progress --memory-limit=-1"

            - name: "PSalm"
              run: "bin/psalm --threads=8"

            - name: "Code Sniffer"
              run: "bin/phpcs -p"

    tests:
        name: "Tests"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  php-version: "8.1"

            - name: "Validate Composer"
              run: "composer validate"

            - name: "Install dependencies"
              run: "composer install --no-interaction --no-progress"

            - name: "Tests"
              run: "bin/paratest --runner=WrapperRunner --colors"
